(function(data){
    var canvas = document.getElementById('hexmap');
	/*
		python to generate json: at https://trinket.io/python/2a713e9b2d
		import random
		print '['
		for i in range(1,28):
			for j in range(1,18):
			  player = random.randint(1, 10)
			  unit = random.randint(0, 5)
			  resource = random.randint(1, 4)
			  speed = random.randint(1, 3)
			  print '{"x":"'+str(i)+'","y":"'+str(j)+'","unit":"'+str(unit)+'","unit":"'+str(unit)+'","owner":"player'+str(player)+'","resource":"'+str(resource)+'","harvestSpeed":"'+str(speed)+'"},'
		print '];'
	*/
	var data =  [
{"x":"1","y":"1","unit":"0","unit":"0","owner":"player5","resource":"2","harvestSpeed":"3"},
{"x":"1","y":"2","unit":"1","unit":"1","owner":"player7","resource":"4","harvestSpeed":"3"},
{"x":"1","y":"3","unit":"1","unit":"1","owner":"player2","resource":"1","harvestSpeed":"3"},
{"x":"1","y":"4","unit":"2","unit":"2","owner":"player10","resource":"4","harvestSpeed":"2"},
{"x":"1","y":"5","unit":"0","unit":"0","owner":"player9","resource":"3","harvestSpeed":"1"},
{"x":"1","y":"6","unit":"0","unit":"0","owner":"player4","resource":"3","harvestSpeed":"2"},
{"x":"1","y":"7","unit":"0","unit":"0","owner":"player7","resource":"2","harvestSpeed":"2"},
{"x":"1","y":"8","unit":"2","unit":"2","owner":"player8","resource":"4","harvestSpeed":"3"},
{"x":"1","y":"9","unit":"2","unit":"2","owner":"player3","resource":"4","harvestSpeed":"3"},
{"x":"1","y":"10","unit":"2","unit":"2","owner":"player1","resource":"4","harvestSpeed":"3"},
{"x":"1","y":"11","unit":"1","unit":"1","owner":"player4","resource":"4","harvestSpeed":"1"},
{"x":"1","y":"12","unit":"2","unit":"2","owner":"player1","resource":"3","harvestSpeed":"1"},
{"x":"1","y":"13","unit":"0","unit":"0","owner":"player4","resource":"4","harvestSpeed":"3"},
{"x":"1","y":"14","unit":"2","unit":"2","owner":"player6","resource":"4","harvestSpeed":"2"},
{"x":"1","y":"15","unit":"3","unit":"3","owner":"player9","resource":"3","harvestSpeed":"3"},
{"x":"1","y":"16","unit":"5","unit":"5","owner":"player5","resource":"3","harvestSpeed":"1"},
{"x":"1","y":"17","unit":"0","unit":"0","owner":"player10","resource":"2","harvestSpeed":"3"},
{"x":"2","y":"1","unit":"5","unit":"5","owner":"player3","resource":"4","harvestSpeed":"3"},
{"x":"2","y":"2","unit":"2","unit":"2","owner":"player7","resource":"1","harvestSpeed":"1"},
{"x":"2","y":"3","unit":"0","unit":"0","owner":"player9","resource":"4","harvestSpeed":"3"},
{"x":"2","y":"4","unit":"2","unit":"2","owner":"player1","resource":"3","harvestSpeed":"1"},
{"x":"2","y":"5","unit":"3","unit":"3","owner":"player1","resource":"3","harvestSpeed":"3"},
{"x":"2","y":"6","unit":"1","unit":"1","owner":"player9","resource":"2","harvestSpeed":"2"},
{"x":"2","y":"7","unit":"3","unit":"3","owner":"player7","resource":"4","harvestSpeed":"3"},
{"x":"2","y":"8","unit":"3","unit":"3","owner":"player2","resource":"2","harvestSpeed":"1"},
{"x":"2","y":"9","unit":"4","unit":"4","owner":"player9","resource":"2","harvestSpeed":"2"},
{"x":"2","y":"10","unit":"5","unit":"5","owner":"player4","resource":"4","harvestSpeed":"2"},
{"x":"2","y":"11","unit":"2","unit":"2","owner":"player4","resource":"3","harvestSpeed":"3"},
{"x":"2","y":"12","unit":"0","unit":"0","owner":"player2","resource":"3","harvestSpeed":"3"},
{"x":"2","y":"13","unit":"4","unit":"4","owner":"player9","resource":"4","harvestSpeed":"2"},
{"x":"2","y":"14","unit":"0","unit":"0","owner":"player1","resource":"2","harvestSpeed":"3"},
{"x":"2","y":"15","unit":"2","unit":"2","owner":"player2","resource":"1","harvestSpeed":"3"},
{"x":"2","y":"16","unit":"3","unit":"3","owner":"player7","resource":"1","harvestSpeed":"2"},
{"x":"2","y":"17","unit":"1","unit":"1","owner":"player2","resource":"3","harvestSpeed":"3"},
{"x":"3","y":"1","unit":"4","unit":"4","owner":"player6","resource":"2","harvestSpeed":"3"},
{"x":"3","y":"2","unit":"1","unit":"1","owner":"player8","resource":"1","harvestSpeed":"2"},
{"x":"3","y":"3","unit":"4","unit":"4","owner":"player1","resource":"3","harvestSpeed":"2"},
{"x":"3","y":"4","unit":"3","unit":"3","owner":"player8","resource":"2","harvestSpeed":"2"},
{"x":"3","y":"5","unit":"3","unit":"3","owner":"player10","resource":"1","harvestSpeed":"2"},
{"x":"3","y":"6","unit":"0","unit":"0","owner":"player7","resource":"4","harvestSpeed":"2"},
{"x":"3","y":"7","unit":"4","unit":"4","owner":"player5","resource":"2","harvestSpeed":"3"},
{"x":"3","y":"8","unit":"0","unit":"0","owner":"player4","resource":"4","harvestSpeed":"3"},
{"x":"3","y":"9","unit":"1","unit":"1","owner":"player6","resource":"3","harvestSpeed":"3"},
{"x":"3","y":"10","unit":"3","unit":"3","owner":"player7","resource":"1","harvestSpeed":"3"},
{"x":"3","y":"11","unit":"3","unit":"3","owner":"player9","resource":"3","harvestSpeed":"3"},
{"x":"3","y":"12","unit":"1","unit":"1","owner":"player7","resource":"1","harvestSpeed":"1"},
{"x":"3","y":"13","unit":"0","unit":"0","owner":"player3","resource":"1","harvestSpeed":"1"},
{"x":"3","y":"14","unit":"1","unit":"1","owner":"player6","resource":"2","harvestSpeed":"1"},
{"x":"3","y":"15","unit":"2","unit":"2","owner":"player6","resource":"3","harvestSpeed":"1"},
{"x":"3","y":"16","unit":"4","unit":"4","owner":"player6","resource":"2","harvestSpeed":"1"},
{"x":"3","y":"17","unit":"2","unit":"2","owner":"player8","resource":"1","harvestSpeed":"2"},
{"x":"4","y":"1","unit":"5","unit":"5","owner":"player10","resource":"4","harvestSpeed":"3"},
{"x":"4","y":"2","unit":"4","unit":"4","owner":"player2","resource":"3","harvestSpeed":"3"},
{"x":"4","y":"3","unit":"0","unit":"0","owner":"player6","resource":"4","harvestSpeed":"2"},
{"x":"4","y":"4","unit":"4","unit":"4","owner":"player6","resource":"2","harvestSpeed":"3"},
{"x":"4","y":"5","unit":"5","unit":"5","owner":"player2","resource":"4","harvestSpeed":"3"},
{"x":"4","y":"6","unit":"2","unit":"2","owner":"player6","resource":"4","harvestSpeed":"2"},
{"x":"4","y":"7","unit":"1","unit":"1","owner":"player3","resource":"3","harvestSpeed":"2"},
{"x":"4","y":"8","unit":"2","unit":"2","owner":"player10","resource":"2","harvestSpeed":"3"},
{"x":"4","y":"9","unit":"4","unit":"4","owner":"player5","resource":"2","harvestSpeed":"1"},
{"x":"4","y":"10","unit":"1","unit":"1","owner":"player10","resource":"2","harvestSpeed":"2"},
{"x":"4","y":"11","unit":"1","unit":"1","owner":"player10","resource":"4","harvestSpeed":"2"},
{"x":"4","y":"12","unit":"5","unit":"5","owner":"player7","resource":"4","harvestSpeed":"1"},
{"x":"4","y":"13","unit":"3","unit":"3","owner":"player10","resource":"1","harvestSpeed":"2"},
{"x":"4","y":"14","unit":"4","unit":"4","owner":"player7","resource":"3","harvestSpeed":"2"},
{"x":"4","y":"15","unit":"3","unit":"3","owner":"player2","resource":"1","harvestSpeed":"1"},
{"x":"4","y":"16","unit":"2","unit":"2","owner":"player4","resource":"3","harvestSpeed":"1"},
{"x":"4","y":"17","unit":"0","unit":"0","owner":"player1","resource":"2","harvestSpeed":"2"},
{"x":"5","y":"1","unit":"3","unit":"3","owner":"player7","resource":"4","harvestSpeed":"1"},
{"x":"5","y":"2","unit":"1","unit":"1","owner":"player5","resource":"4","harvestSpeed":"3"},
{"x":"5","y":"3","unit":"4","unit":"4","owner":"player9","resource":"3","harvestSpeed":"2"},
{"x":"5","y":"4","unit":"0","unit":"0","owner":"player1","resource":"3","harvestSpeed":"2"},
{"x":"5","y":"5","unit":"2","unit":"2","owner":"player9","resource":"1","harvestSpeed":"2"},
{"x":"5","y":"6","unit":"5","unit":"5","owner":"player4","resource":"2","harvestSpeed":"2"},
{"x":"5","y":"7","unit":"1","unit":"1","owner":"player2","resource":"2","harvestSpeed":"3"},
{"x":"5","y":"8","unit":"2","unit":"2","owner":"player6","resource":"2","harvestSpeed":"1"},
{"x":"5","y":"9","unit":"4","unit":"4","owner":"player6","resource":"2","harvestSpeed":"3"},
{"x":"5","y":"10","unit":"1","unit":"1","owner":"player4","resource":"1","harvestSpeed":"3"},
{"x":"5","y":"11","unit":"4","unit":"4","owner":"player1","resource":"4","harvestSpeed":"1"},
{"x":"5","y":"12","unit":"4","unit":"4","owner":"player3","resource":"4","harvestSpeed":"1"},
{"x":"5","y":"13","unit":"5","unit":"5","owner":"player7","resource":"4","harvestSpeed":"1"},
{"x":"5","y":"14","unit":"5","unit":"5","owner":"player10","resource":"3","harvestSpeed":"1"},
{"x":"5","y":"15","unit":"5","unit":"5","owner":"player7","resource":"4","harvestSpeed":"1"},
{"x":"5","y":"16","unit":"5","unit":"5","owner":"player8","resource":"3","harvestSpeed":"1"},
{"x":"5","y":"17","unit":"5","unit":"5","owner":"player4","resource":"4","harvestSpeed":"3"},
{"x":"6","y":"1","unit":"2","unit":"2","owner":"player7","resource":"3","harvestSpeed":"2"},
{"x":"6","y":"2","unit":"3","unit":"3","owner":"player8","resource":"1","harvestSpeed":"1"},
{"x":"6","y":"3","unit":"3","unit":"3","owner":"player2","resource":"2","harvestSpeed":"1"},
{"x":"6","y":"4","unit":"1","unit":"1","owner":"player5","resource":"1","harvestSpeed":"3"},
{"x":"6","y":"5","unit":"5","unit":"5","owner":"player8","resource":"2","harvestSpeed":"3"},
{"x":"6","y":"6","unit":"4","unit":"4","owner":"player3","resource":"4","harvestSpeed":"2"},
{"x":"6","y":"7","unit":"5","unit":"5","owner":"player6","resource":"1","harvestSpeed":"1"},
{"x":"6","y":"8","unit":"0","unit":"0","owner":"player4","resource":"4","harvestSpeed":"1"},
{"x":"6","y":"9","unit":"5","unit":"5","owner":"player9","resource":"4","harvestSpeed":"3"},
{"x":"6","y":"10","unit":"1","unit":"1","owner":"player6","resource":"2","harvestSpeed":"3"},
{"x":"6","y":"11","unit":"3","unit":"3","owner":"player5","resource":"1","harvestSpeed":"2"},
{"x":"6","y":"12","unit":"0","unit":"0","owner":"player9","resource":"1","harvestSpeed":"1"},
{"x":"6","y":"13","unit":"5","unit":"5","owner":"player2","resource":"2","harvestSpeed":"2"},
{"x":"6","y":"14","unit":"5","unit":"5","owner":"player6","resource":"3","harvestSpeed":"1"},
{"x":"6","y":"15","unit":"0","unit":"0","owner":"player8","resource":"4","harvestSpeed":"2"},
{"x":"6","y":"16","unit":"0","unit":"0","owner":"player4","resource":"1","harvestSpeed":"3"},
{"x":"6","y":"17","unit":"0","unit":"0","owner":"player2","resource":"2","harvestSpeed":"2"},
{"x":"7","y":"1","unit":"1","unit":"1","owner":"player3","resource":"3","harvestSpeed":"1"},
{"x":"7","y":"2","unit":"1","unit":"1","owner":"player10","resource":"2","harvestSpeed":"2"},
{"x":"7","y":"3","unit":"1","unit":"1","owner":"player9","resource":"1","harvestSpeed":"2"},
{"x":"7","y":"4","unit":"3","unit":"3","owner":"player1","resource":"3","harvestSpeed":"1"},
{"x":"7","y":"5","unit":"3","unit":"3","owner":"player6","resource":"1","harvestSpeed":"1"},
{"x":"7","y":"6","unit":"5","unit":"5","owner":"player5","resource":"3","harvestSpeed":"3"},
{"x":"7","y":"7","unit":"0","unit":"0","owner":"player8","resource":"3","harvestSpeed":"2"},
{"x":"7","y":"8","unit":"4","unit":"4","owner":"player4","resource":"4","harvestSpeed":"3"},
{"x":"7","y":"9","unit":"4","unit":"4","owner":"player4","resource":"1","harvestSpeed":"1"},
{"x":"7","y":"10","unit":"4","unit":"4","owner":"player3","resource":"1","harvestSpeed":"3"},
{"x":"7","y":"11","unit":"0","unit":"0","owner":"player9","resource":"2","harvestSpeed":"1"},
{"x":"7","y":"12","unit":"3","unit":"3","owner":"player3","resource":"3","harvestSpeed":"3"},
{"x":"7","y":"13","unit":"1","unit":"1","owner":"player6","resource":"1","harvestSpeed":"3"},
{"x":"7","y":"14","unit":"3","unit":"3","owner":"player9","resource":"2","harvestSpeed":"1"},
{"x":"7","y":"15","unit":"5","unit":"5","owner":"player6","resource":"2","harvestSpeed":"1"},
{"x":"7","y":"16","unit":"5","unit":"5","owner":"player4","resource":"3","harvestSpeed":"1"},
{"x":"7","y":"17","unit":"4","unit":"4","owner":"player10","resource":"3","harvestSpeed":"2"},
{"x":"8","y":"1","unit":"4","unit":"4","owner":"player5","resource":"3","harvestSpeed":"3"},
{"x":"8","y":"2","unit":"3","unit":"3","owner":"player1","resource":"2","harvestSpeed":"3"},
{"x":"8","y":"3","unit":"0","unit":"0","owner":"player1","resource":"3","harvestSpeed":"1"},
{"x":"8","y":"4","unit":"4","unit":"4","owner":"player9","resource":"4","harvestSpeed":"2"},
{"x":"8","y":"5","unit":"0","unit":"0","owner":"player3","resource":"3","harvestSpeed":"3"},
{"x":"8","y":"6","unit":"1","unit":"1","owner":"player10","resource":"4","harvestSpeed":"2"},
{"x":"8","y":"7","unit":"4","unit":"4","owner":"player2","resource":"4","harvestSpeed":"1"},
{"x":"8","y":"8","unit":"3","unit":"3","owner":"player1","resource":"4","harvestSpeed":"3"},
{"x":"8","y":"9","unit":"2","unit":"2","owner":"player3","resource":"1","harvestSpeed":"3"},
{"x":"8","y":"10","unit":"5","unit":"5","owner":"player3","resource":"3","harvestSpeed":"3"},
{"x":"8","y":"11","unit":"3","unit":"3","owner":"player10","resource":"4","harvestSpeed":"2"},
{"x":"8","y":"12","unit":"1","unit":"1","owner":"player10","resource":"2","harvestSpeed":"3"},
{"x":"8","y":"13","unit":"4","unit":"4","owner":"player10","resource":"2","harvestSpeed":"2"},
{"x":"8","y":"14","unit":"0","unit":"0","owner":"player9","resource":"2","harvestSpeed":"2"},
{"x":"8","y":"15","unit":"1","unit":"1","owner":"player2","resource":"2","harvestSpeed":"3"},
{"x":"8","y":"16","unit":"0","unit":"0","owner":"player10","resource":"4","harvestSpeed":"1"},
{"x":"8","y":"17","unit":"5","unit":"5","owner":"player5","resource":"2","harvestSpeed":"2"},
{"x":"9","y":"1","unit":"0","unit":"0","owner":"player3","resource":"1","harvestSpeed":"3"},
{"x":"9","y":"2","unit":"5","unit":"5","owner":"player2","resource":"4","harvestSpeed":"1"},
{"x":"9","y":"3","unit":"2","unit":"2","owner":"player5","resource":"3","harvestSpeed":"3"},
{"x":"9","y":"4","unit":"2","unit":"2","owner":"player5","resource":"4","harvestSpeed":"2"},
{"x":"9","y":"5","unit":"0","unit":"0","owner":"player3","resource":"1","harvestSpeed":"1"},
{"x":"9","y":"6","unit":"5","unit":"5","owner":"player4","resource":"2","harvestSpeed":"3"},
{"x":"9","y":"7","unit":"2","unit":"2","owner":"player3","resource":"3","harvestSpeed":"2"},
{"x":"9","y":"8","unit":"4","unit":"4","owner":"player4","resource":"3","harvestSpeed":"3"},
{"x":"9","y":"9","unit":"3","unit":"3","owner":"player9","resource":"2","harvestSpeed":"1"},
{"x":"9","y":"10","unit":"4","unit":"4","owner":"player3","resource":"1","harvestSpeed":"1"},
{"x":"9","y":"11","unit":"4","unit":"4","owner":"player5","resource":"4","harvestSpeed":"3"},
{"x":"9","y":"12","unit":"4","unit":"4","owner":"player1","resource":"3","harvestSpeed":"2"},
{"x":"9","y":"13","unit":"0","unit":"0","owner":"player9","resource":"3","harvestSpeed":"3"},
{"x":"9","y":"14","unit":"5","unit":"5","owner":"player9","resource":"3","harvestSpeed":"2"},
{"x":"9","y":"15","unit":"3","unit":"3","owner":"player2","resource":"4","harvestSpeed":"3"},
{"x":"9","y":"16","unit":"2","unit":"2","owner":"player10","resource":"3","harvestSpeed":"2"},
{"x":"9","y":"17","unit":"2","unit":"2","owner":"player4","resource":"2","harvestSpeed":"1"},
{"x":"10","y":"1","unit":"0","unit":"0","owner":"player7","resource":"1","harvestSpeed":"3"},
{"x":"10","y":"2","unit":"0","unit":"0","owner":"player9","resource":"2","harvestSpeed":"1"},
{"x":"10","y":"3","unit":"0","unit":"0","owner":"player5","resource":"4","harvestSpeed":"2"},
{"x":"10","y":"4","unit":"5","unit":"5","owner":"player6","resource":"4","harvestSpeed":"2"},
{"x":"10","y":"5","unit":"2","unit":"2","owner":"player3","resource":"4","harvestSpeed":"3"},
{"x":"10","y":"6","unit":"3","unit":"3","owner":"player8","resource":"2","harvestSpeed":"2"},
{"x":"10","y":"7","unit":"2","unit":"2","owner":"player7","resource":"2","harvestSpeed":"2"},
{"x":"10","y":"8","unit":"3","unit":"3","owner":"player5","resource":"4","harvestSpeed":"3"},
{"x":"10","y":"9","unit":"5","unit":"5","owner":"player6","resource":"1","harvestSpeed":"1"},
{"x":"10","y":"10","unit":"1","unit":"1","owner":"player10","resource":"1","harvestSpeed":"2"},
{"x":"10","y":"11","unit":"3","unit":"3","owner":"player7","resource":"2","harvestSpeed":"1"},
{"x":"10","y":"12","unit":"4","unit":"4","owner":"player6","resource":"3","harvestSpeed":"1"},
{"x":"10","y":"13","unit":"5","unit":"5","owner":"player2","resource":"3","harvestSpeed":"3"},
{"x":"10","y":"14","unit":"1","unit":"1","owner":"player6","resource":"2","harvestSpeed":"1"},
{"x":"10","y":"15","unit":"0","unit":"0","owner":"player10","resource":"1","harvestSpeed":"1"},
{"x":"10","y":"16","unit":"5","unit":"5","owner":"player1","resource":"1","harvestSpeed":"2"},
{"x":"10","y":"17","unit":"1","unit":"1","owner":"player6","resource":"1","harvestSpeed":"2"},
{"x":"11","y":"1","unit":"2","unit":"2","owner":"player4","resource":"2","harvestSpeed":"2"},
{"x":"11","y":"2","unit":"4","unit":"4","owner":"player5","resource":"3","harvestSpeed":"2"},
{"x":"11","y":"3","unit":"0","unit":"0","owner":"player1","resource":"1","harvestSpeed":"3"},
{"x":"11","y":"4","unit":"0","unit":"0","owner":"player6","resource":"4","harvestSpeed":"2"},
{"x":"11","y":"5","unit":"5","unit":"5","owner":"player2","resource":"2","harvestSpeed":"1"},
{"x":"11","y":"6","unit":"3","unit":"3","owner":"player7","resource":"2","harvestSpeed":"3"},
{"x":"11","y":"7","unit":"0","unit":"0","owner":"player8","resource":"4","harvestSpeed":"1"},
{"x":"11","y":"8","unit":"4","unit":"4","owner":"player8","resource":"1","harvestSpeed":"1"},
{"x":"11","y":"9","unit":"3","unit":"3","owner":"player2","resource":"4","harvestSpeed":"2"},
{"x":"11","y":"10","unit":"3","unit":"3","owner":"player5","resource":"1","harvestSpeed":"2"},
{"x":"11","y":"11","unit":"2","unit":"2","owner":"player7","resource":"2","harvestSpeed":"1"},
{"x":"11","y":"12","unit":"2","unit":"2","owner":"player5","resource":"2","harvestSpeed":"1"},
{"x":"11","y":"13","unit":"2","unit":"2","owner":"player1","resource":"2","harvestSpeed":"3"},
{"x":"11","y":"14","unit":"1","unit":"1","owner":"player8","resource":"2","harvestSpeed":"3"},
{"x":"11","y":"15","unit":"1","unit":"1","owner":"player8","resource":"1","harvestSpeed":"3"},
{"x":"11","y":"16","unit":"2","unit":"2","owner":"player2","resource":"1","harvestSpeed":"2"},
{"x":"11","y":"17","unit":"4","unit":"4","owner":"player2","resource":"2","harvestSpeed":"3"},
{"x":"12","y":"1","unit":"4","unit":"4","owner":"player9","resource":"2","harvestSpeed":"3"},
{"x":"12","y":"2","unit":"1","unit":"1","owner":"player1","resource":"4","harvestSpeed":"3"},
{"x":"12","y":"3","unit":"3","unit":"3","owner":"player8","resource":"2","harvestSpeed":"3"},
{"x":"12","y":"4","unit":"2","unit":"2","owner":"player3","resource":"1","harvestSpeed":"2"},
{"x":"12","y":"5","unit":"0","unit":"0","owner":"player4","resource":"4","harvestSpeed":"2"},
{"x":"12","y":"6","unit":"0","unit":"0","owner":"player10","resource":"4","harvestSpeed":"3"},
{"x":"12","y":"7","unit":"2","unit":"2","owner":"player6","resource":"4","harvestSpeed":"2"},
{"x":"12","y":"8","unit":"5","unit":"5","owner":"player10","resource":"3","harvestSpeed":"3"},
{"x":"12","y":"9","unit":"2","unit":"2","owner":"player3","resource":"2","harvestSpeed":"2"},
{"x":"12","y":"10","unit":"5","unit":"5","owner":"player8","resource":"3","harvestSpeed":"1"},
{"x":"12","y":"11","unit":"3","unit":"3","owner":"player5","resource":"2","harvestSpeed":"3"},
{"x":"12","y":"12","unit":"1","unit":"1","owner":"player9","resource":"3","harvestSpeed":"1"},
{"x":"12","y":"13","unit":"5","unit":"5","owner":"player4","resource":"3","harvestSpeed":"2"},
{"x":"12","y":"14","unit":"0","unit":"0","owner":"player8","resource":"4","harvestSpeed":"1"},
{"x":"12","y":"15","unit":"1","unit":"1","owner":"player9","resource":"3","harvestSpeed":"1"},
{"x":"12","y":"16","unit":"5","unit":"5","owner":"player3","resource":"4","harvestSpeed":"2"},
{"x":"12","y":"17","unit":"5","unit":"5","owner":"player10","resource":"2","harvestSpeed":"2"},
{"x":"13","y":"1","unit":"2","unit":"2","owner":"player4","resource":"3","harvestSpeed":"2"},
{"x":"13","y":"2","unit":"5","unit":"5","owner":"player2","resource":"2","harvestSpeed":"2"},
{"x":"13","y":"3","unit":"4","unit":"4","owner":"player8","resource":"1","harvestSpeed":"3"},
{"x":"13","y":"4","unit":"5","unit":"5","owner":"player10","resource":"4","harvestSpeed":"3"},
{"x":"13","y":"5","unit":"1","unit":"1","owner":"player4","resource":"2","harvestSpeed":"2"},
{"x":"13","y":"6","unit":"4","unit":"4","owner":"player9","resource":"2","harvestSpeed":"3"},
{"x":"13","y":"7","unit":"2","unit":"2","owner":"player5","resource":"3","harvestSpeed":"2"},
{"x":"13","y":"8","unit":"5","unit":"5","owner":"player5","resource":"3","harvestSpeed":"2"},
{"x":"13","y":"9","unit":"4","unit":"4","owner":"player8","resource":"1","harvestSpeed":"3"},
{"x":"13","y":"10","unit":"4","unit":"4","owner":"player1","resource":"3","harvestSpeed":"2"},
{"x":"13","y":"11","unit":"0","unit":"0","owner":"player3","resource":"4","harvestSpeed":"2"},
{"x":"13","y":"12","unit":"3","unit":"3","owner":"player3","resource":"3","harvestSpeed":"1"},
{"x":"13","y":"13","unit":"5","unit":"5","owner":"player2","resource":"3","harvestSpeed":"1"},
{"x":"13","y":"14","unit":"5","unit":"5","owner":"player1","resource":"2","harvestSpeed":"1"},
{"x":"13","y":"15","unit":"5","unit":"5","owner":"player2","resource":"2","harvestSpeed":"3"},
{"x":"13","y":"16","unit":"1","unit":"1","owner":"player3","resource":"3","harvestSpeed":"3"},
{"x":"13","y":"17","unit":"5","unit":"5","owner":"player1","resource":"2","harvestSpeed":"1"},
{"x":"14","y":"1","unit":"1","unit":"1","owner":"player6","resource":"3","harvestSpeed":"1"},
{"x":"14","y":"2","unit":"0","unit":"0","owner":"player9","resource":"3","harvestSpeed":"3"},
{"x":"14","y":"3","unit":"3","unit":"3","owner":"player1","resource":"1","harvestSpeed":"3"},
{"x":"14","y":"4","unit":"5","unit":"5","owner":"player9","resource":"2","harvestSpeed":"2"},
{"x":"14","y":"5","unit":"5","unit":"5","owner":"player9","resource":"3","harvestSpeed":"3"},
{"x":"14","y":"6","unit":"3","unit":"3","owner":"player2","resource":"1","harvestSpeed":"2"},
{"x":"14","y":"7","unit":"3","unit":"3","owner":"player3","resource":"4","harvestSpeed":"1"},
{"x":"14","y":"8","unit":"4","unit":"4","owner":"player1","resource":"1","harvestSpeed":"2"},
{"x":"14","y":"9","unit":"3","unit":"3","owner":"player5","resource":"2","harvestSpeed":"1"},
{"x":"14","y":"10","unit":"2","unit":"2","owner":"player4","resource":"1","harvestSpeed":"2"},
{"x":"14","y":"11","unit":"2","unit":"2","owner":"player9","resource":"4","harvestSpeed":"2"},
{"x":"14","y":"12","unit":"1","unit":"1","owner":"player7","resource":"1","harvestSpeed":"3"},
{"x":"14","y":"13","unit":"3","unit":"3","owner":"player2","resource":"2","harvestSpeed":"1"},
{"x":"14","y":"14","unit":"1","unit":"1","owner":"player7","resource":"3","harvestSpeed":"2"},
{"x":"14","y":"15","unit":"0","unit":"0","owner":"player1","resource":"2","harvestSpeed":"2"},
{"x":"14","y":"16","unit":"2","unit":"2","owner":"player2","resource":"4","harvestSpeed":"2"},
{"x":"14","y":"17","unit":"2","unit":"2","owner":"player10","resource":"4","harvestSpeed":"3"},
{"x":"15","y":"1","unit":"2","unit":"2","owner":"player2","resource":"2","harvestSpeed":"3"},
{"x":"15","y":"2","unit":"1","unit":"1","owner":"player8","resource":"2","harvestSpeed":"3"},
{"x":"15","y":"3","unit":"3","unit":"3","owner":"player9","resource":"4","harvestSpeed":"3"},
{"x":"15","y":"4","unit":"1","unit":"1","owner":"player5","resource":"4","harvestSpeed":"3"},
{"x":"15","y":"5","unit":"0","unit":"0","owner":"player7","resource":"1","harvestSpeed":"1"},
{"x":"15","y":"6","unit":"5","unit":"5","owner":"player7","resource":"2","harvestSpeed":"2"},
{"x":"15","y":"7","unit":"4","unit":"4","owner":"player7","resource":"4","harvestSpeed":"1"},
{"x":"15","y":"8","unit":"5","unit":"5","owner":"player4","resource":"3","harvestSpeed":"3"},
{"x":"15","y":"9","unit":"0","unit":"0","owner":"player1","resource":"2","harvestSpeed":"1"},
{"x":"15","y":"10","unit":"4","unit":"4","owner":"player6","resource":"4","harvestSpeed":"2"},
{"x":"15","y":"11","unit":"0","unit":"0","owner":"player9","resource":"3","harvestSpeed":"2"},
{"x":"15","y":"12","unit":"2","unit":"2","owner":"player3","resource":"4","harvestSpeed":"2"},
{"x":"15","y":"13","unit":"0","unit":"0","owner":"player8","resource":"3","harvestSpeed":"3"},
{"x":"15","y":"14","unit":"4","unit":"4","owner":"player9","resource":"1","harvestSpeed":"2"},
{"x":"15","y":"15","unit":"1","unit":"1","owner":"player7","resource":"2","harvestSpeed":"3"},
{"x":"15","y":"16","unit":"1","unit":"1","owner":"player6","resource":"3","harvestSpeed":"2"},
{"x":"15","y":"17","unit":"2","unit":"2","owner":"player8","resource":"2","harvestSpeed":"1"},
{"x":"16","y":"1","unit":"1","unit":"1","owner":"player8","resource":"3","harvestSpeed":"1"},
{"x":"16","y":"2","unit":"3","unit":"3","owner":"player5","resource":"4","harvestSpeed":"3"},
{"x":"16","y":"3","unit":"3","unit":"3","owner":"player10","resource":"1","harvestSpeed":"2"},
{"x":"16","y":"4","unit":"3","unit":"3","owner":"player1","resource":"2","harvestSpeed":"2"},
{"x":"16","y":"5","unit":"5","unit":"5","owner":"player6","resource":"1","harvestSpeed":"3"},
{"x":"16","y":"6","unit":"3","unit":"3","owner":"player10","resource":"2","harvestSpeed":"2"},
{"x":"16","y":"7","unit":"2","unit":"2","owner":"player5","resource":"3","harvestSpeed":"3"},
{"x":"16","y":"8","unit":"5","unit":"5","owner":"player1","resource":"4","harvestSpeed":"1"},
{"x":"16","y":"9","unit":"5","unit":"5","owner":"player7","resource":"1","harvestSpeed":"1"},
{"x":"16","y":"10","unit":"3","unit":"3","owner":"player1","resource":"4","harvestSpeed":"2"},
{"x":"16","y":"11","unit":"4","unit":"4","owner":"player4","resource":"4","harvestSpeed":"2"},
{"x":"16","y":"12","unit":"4","unit":"4","owner":"player4","resource":"3","harvestSpeed":"1"},
{"x":"16","y":"13","unit":"5","unit":"5","owner":"player3","resource":"3","harvestSpeed":"2"},
{"x":"16","y":"14","unit":"5","unit":"5","owner":"player6","resource":"4","harvestSpeed":"2"},
{"x":"16","y":"15","unit":"2","unit":"2","owner":"player3","resource":"4","harvestSpeed":"2"},
{"x":"16","y":"16","unit":"2","unit":"2","owner":"player1","resource":"1","harvestSpeed":"3"},
{"x":"16","y":"17","unit":"1","unit":"1","owner":"player6","resource":"2","harvestSpeed":"1"},
{"x":"17","y":"1","unit":"5","unit":"5","owner":"player5","resource":"4","harvestSpeed":"2"},
{"x":"17","y":"2","unit":"5","unit":"5","owner":"player1","resource":"4","harvestSpeed":"2"},
{"x":"17","y":"3","unit":"5","unit":"5","owner":"player6","resource":"1","harvestSpeed":"3"},
{"x":"17","y":"4","unit":"1","unit":"1","owner":"player6","resource":"2","harvestSpeed":"2"},
{"x":"17","y":"5","unit":"0","unit":"0","owner":"player9","resource":"2","harvestSpeed":"3"},
{"x":"17","y":"6","unit":"2","unit":"2","owner":"player10","resource":"4","harvestSpeed":"2"},
{"x":"17","y":"7","unit":"1","unit":"1","owner":"player7","resource":"2","harvestSpeed":"2"},
{"x":"17","y":"8","unit":"4","unit":"4","owner":"player2","resource":"1","harvestSpeed":"3"},
{"x":"17","y":"9","unit":"4","unit":"4","owner":"player6","resource":"1","harvestSpeed":"3"},
{"x":"17","y":"10","unit":"4","unit":"4","owner":"player1","resource":"3","harvestSpeed":"1"},
{"x":"17","y":"11","unit":"5","unit":"5","owner":"player8","resource":"1","harvestSpeed":"3"},
{"x":"17","y":"12","unit":"1","unit":"1","owner":"player2","resource":"1","harvestSpeed":"2"},
{"x":"17","y":"13","unit":"0","unit":"0","owner":"player8","resource":"2","harvestSpeed":"2"},
{"x":"17","y":"14","unit":"3","unit":"3","owner":"player1","resource":"1","harvestSpeed":"1"},
{"x":"17","y":"15","unit":"4","unit":"4","owner":"player2","resource":"4","harvestSpeed":"3"},
{"x":"17","y":"16","unit":"5","unit":"5","owner":"player4","resource":"1","harvestSpeed":"2"},
{"x":"17","y":"17","unit":"1","unit":"1","owner":"player8","resource":"3","harvestSpeed":"3"},
{"x":"18","y":"1","unit":"1","unit":"1","owner":"player8","resource":"1","harvestSpeed":"3"},
{"x":"18","y":"2","unit":"2","unit":"2","owner":"player7","resource":"4","harvestSpeed":"2"},
{"x":"18","y":"3","unit":"2","unit":"2","owner":"player6","resource":"1","harvestSpeed":"2"},
{"x":"18","y":"4","unit":"0","unit":"0","owner":"player5","resource":"2","harvestSpeed":"1"},
{"x":"18","y":"5","unit":"1","unit":"1","owner":"player3","resource":"4","harvestSpeed":"2"},
{"x":"18","y":"6","unit":"1","unit":"1","owner":"player10","resource":"1","harvestSpeed":"3"},
{"x":"18","y":"7","unit":"3","unit":"3","owner":"player2","resource":"4","harvestSpeed":"1"},
{"x":"18","y":"8","unit":"4","unit":"4","owner":"player6","resource":"4","harvestSpeed":"3"},
{"x":"18","y":"9","unit":"4","unit":"4","owner":"player2","resource":"4","harvestSpeed":"1"},
{"x":"18","y":"10","unit":"3","unit":"3","owner":"player4","resource":"2","harvestSpeed":"3"},
{"x":"18","y":"11","unit":"5","unit":"5","owner":"player4","resource":"1","harvestSpeed":"2"},
{"x":"18","y":"12","unit":"2","unit":"2","owner":"player7","resource":"2","harvestSpeed":"1"},
{"x":"18","y":"13","unit":"4","unit":"4","owner":"player3","resource":"4","harvestSpeed":"3"},
{"x":"18","y":"14","unit":"5","unit":"5","owner":"player8","resource":"4","harvestSpeed":"2"},
{"x":"18","y":"15","unit":"4","unit":"4","owner":"player5","resource":"2","harvestSpeed":"1"},
{"x":"18","y":"16","unit":"5","unit":"5","owner":"player3","resource":"2","harvestSpeed":"3"},
{"x":"18","y":"17","unit":"4","unit":"4","owner":"player5","resource":"2","harvestSpeed":"2"},
{"x":"19","y":"1","unit":"5","unit":"5","owner":"player7","resource":"4","harvestSpeed":"3"},
{"x":"19","y":"2","unit":"3","unit":"3","owner":"player8","resource":"1","harvestSpeed":"1"},
{"x":"19","y":"3","unit":"5","unit":"5","owner":"player2","resource":"1","harvestSpeed":"3"},
{"x":"19","y":"4","unit":"3","unit":"3","owner":"player3","resource":"4","harvestSpeed":"2"},
{"x":"19","y":"5","unit":"5","unit":"5","owner":"player8","resource":"3","harvestSpeed":"1"},
{"x":"19","y":"6","unit":"5","unit":"5","owner":"player8","resource":"4","harvestSpeed":"2"},
{"x":"19","y":"7","unit":"4","unit":"4","owner":"player5","resource":"4","harvestSpeed":"3"},
{"x":"19","y":"8","unit":"5","unit":"5","owner":"player7","resource":"2","harvestSpeed":"3"},
{"x":"19","y":"9","unit":"1","unit":"1","owner":"player2","resource":"2","harvestSpeed":"1"},
{"x":"19","y":"10","unit":"3","unit":"3","owner":"player1","resource":"1","harvestSpeed":"3"},
{"x":"19","y":"11","unit":"1","unit":"1","owner":"player9","resource":"1","harvestSpeed":"1"},
{"x":"19","y":"12","unit":"5","unit":"5","owner":"player7","resource":"2","harvestSpeed":"3"},
{"x":"19","y":"13","unit":"5","unit":"5","owner":"player5","resource":"4","harvestSpeed":"2"},
{"x":"19","y":"14","unit":"2","unit":"2","owner":"player2","resource":"3","harvestSpeed":"2"},
{"x":"19","y":"15","unit":"3","unit":"3","owner":"player3","resource":"1","harvestSpeed":"2"},
{"x":"19","y":"16","unit":"0","unit":"0","owner":"player10","resource":"4","harvestSpeed":"1"},
{"x":"19","y":"17","unit":"2","unit":"2","owner":"player8","resource":"1","harvestSpeed":"2"},
{"x":"20","y":"1","unit":"2","unit":"2","owner":"player3","resource":"4","harvestSpeed":"1"},
{"x":"20","y":"2","unit":"2","unit":"2","owner":"player10","resource":"4","harvestSpeed":"3"},
{"x":"20","y":"3","unit":"1","unit":"1","owner":"player10","resource":"1","harvestSpeed":"3"},
{"x":"20","y":"4","unit":"5","unit":"5","owner":"player4","resource":"2","harvestSpeed":"2"},
{"x":"20","y":"5","unit":"4","unit":"4","owner":"player9","resource":"1","harvestSpeed":"1"},
{"x":"20","y":"6","unit":"0","unit":"0","owner":"player10","resource":"1","harvestSpeed":"1"},
{"x":"20","y":"7","unit":"4","unit":"4","owner":"player7","resource":"2","harvestSpeed":"3"},
{"x":"20","y":"8","unit":"3","unit":"3","owner":"player7","resource":"3","harvestSpeed":"3"},
{"x":"20","y":"9","unit":"5","unit":"5","owner":"player8","resource":"4","harvestSpeed":"1"},
{"x":"20","y":"10","unit":"5","unit":"5","owner":"player6","resource":"2","harvestSpeed":"2"},
{"x":"20","y":"11","unit":"5","unit":"5","owner":"player5","resource":"2","harvestSpeed":"1"},
{"x":"20","y":"12","unit":"1","unit":"1","owner":"player2","resource":"2","harvestSpeed":"2"},
{"x":"20","y":"13","unit":"3","unit":"3","owner":"player4","resource":"2","harvestSpeed":"1"},
{"x":"20","y":"14","unit":"0","unit":"0","owner":"player7","resource":"3","harvestSpeed":"3"},
{"x":"20","y":"15","unit":"2","unit":"2","owner":"player5","resource":"4","harvestSpeed":"3"},
{"x":"20","y":"16","unit":"3","unit":"3","owner":"player4","resource":"2","harvestSpeed":"1"},
{"x":"20","y":"17","unit":"2","unit":"2","owner":"player1","resource":"4","harvestSpeed":"1"},
{"x":"21","y":"1","unit":"3","unit":"3","owner":"player10","resource":"3","harvestSpeed":"1"},
{"x":"21","y":"2","unit":"3","unit":"3","owner":"player3","resource":"1","harvestSpeed":"1"},
{"x":"21","y":"3","unit":"5","unit":"5","owner":"player3","resource":"1","harvestSpeed":"1"},
{"x":"21","y":"4","unit":"1","unit":"1","owner":"player10","resource":"2","harvestSpeed":"2"},
{"x":"21","y":"5","unit":"5","unit":"5","owner":"player10","resource":"4","harvestSpeed":"2"},
{"x":"21","y":"6","unit":"0","unit":"0","owner":"player8","resource":"1","harvestSpeed":"3"},
{"x":"21","y":"7","unit":"3","unit":"3","owner":"player9","resource":"4","harvestSpeed":"3"},
{"x":"21","y":"8","unit":"3","unit":"3","owner":"player5","resource":"2","harvestSpeed":"3"},
{"x":"21","y":"9","unit":"3","unit":"3","owner":"player1","resource":"4","harvestSpeed":"2"},
{"x":"21","y":"10","unit":"5","unit":"5","owner":"player4","resource":"3","harvestSpeed":"3"},
{"x":"21","y":"11","unit":"3","unit":"3","owner":"player8","resource":"2","harvestSpeed":"3"},
{"x":"21","y":"12","unit":"2","unit":"2","owner":"player7","resource":"4","harvestSpeed":"2"},
{"x":"21","y":"13","unit":"4","unit":"4","owner":"player7","resource":"2","harvestSpeed":"3"},
{"x":"21","y":"14","unit":"1","unit":"1","owner":"player10","resource":"1","harvestSpeed":"3"},
{"x":"21","y":"15","unit":"0","unit":"0","owner":"player7","resource":"2","harvestSpeed":"3"},
{"x":"21","y":"16","unit":"1","unit":"1","owner":"player1","resource":"3","harvestSpeed":"2"},
{"x":"21","y":"17","unit":"4","unit":"4","owner":"player4","resource":"4","harvestSpeed":"3"},
{"x":"22","y":"1","unit":"0","unit":"0","owner":"player7","resource":"1","harvestSpeed":"1"},
{"x":"22","y":"2","unit":"4","unit":"4","owner":"player3","resource":"3","harvestSpeed":"3"},
{"x":"22","y":"3","unit":"5","unit":"5","owner":"player2","resource":"3","harvestSpeed":"3"},
{"x":"22","y":"4","unit":"2","unit":"2","owner":"player8","resource":"3","harvestSpeed":"2"},
{"x":"22","y":"5","unit":"0","unit":"0","owner":"player2","resource":"3","harvestSpeed":"2"},
{"x":"22","y":"6","unit":"4","unit":"4","owner":"player2","resource":"1","harvestSpeed":"3"},
{"x":"22","y":"7","unit":"2","unit":"2","owner":"player8","resource":"3","harvestSpeed":"1"},
{"x":"22","y":"8","unit":"1","unit":"1","owner":"player4","resource":"3","harvestSpeed":"1"},
{"x":"22","y":"9","unit":"1","unit":"1","owner":"player10","resource":"3","harvestSpeed":"1"},
{"x":"22","y":"10","unit":"4","unit":"4","owner":"player4","resource":"3","harvestSpeed":"3"},
{"x":"22","y":"11","unit":"0","unit":"0","owner":"player2","resource":"1","harvestSpeed":"3"},
{"x":"22","y":"12","unit":"5","unit":"5","owner":"player5","resource":"2","harvestSpeed":"3"},
{"x":"22","y":"13","unit":"2","unit":"2","owner":"player7","resource":"2","harvestSpeed":"3"},
{"x":"22","y":"14","unit":"3","unit":"3","owner":"player7","resource":"4","harvestSpeed":"1"},
{"x":"22","y":"15","unit":"0","unit":"0","owner":"player5","resource":"3","harvestSpeed":"1"},
{"x":"22","y":"16","unit":"0","unit":"0","owner":"player6","resource":"3","harvestSpeed":"3"},
{"x":"22","y":"17","unit":"0","unit":"0","owner":"player5","resource":"1","harvestSpeed":"3"},
{"x":"23","y":"1","unit":"4","unit":"4","owner":"player1","resource":"1","harvestSpeed":"2"},
{"x":"23","y":"2","unit":"4","unit":"4","owner":"player4","resource":"2","harvestSpeed":"1"},
{"x":"23","y":"3","unit":"5","unit":"5","owner":"player10","resource":"2","harvestSpeed":"1"},
{"x":"23","y":"4","unit":"1","unit":"1","owner":"player7","resource":"2","harvestSpeed":"2"},
{"x":"23","y":"5","unit":"1","unit":"1","owner":"player3","resource":"1","harvestSpeed":"2"},
{"x":"23","y":"6","unit":"5","unit":"5","owner":"player2","resource":"4","harvestSpeed":"2"},
{"x":"23","y":"7","unit":"2","unit":"2","owner":"player8","resource":"2","harvestSpeed":"1"},
{"x":"23","y":"8","unit":"4","unit":"4","owner":"player6","resource":"3","harvestSpeed":"1"},
{"x":"23","y":"9","unit":"1","unit":"1","owner":"player4","resource":"1","harvestSpeed":"3"},
{"x":"23","y":"10","unit":"4","unit":"4","owner":"player3","resource":"1","harvestSpeed":"3"},
{"x":"23","y":"11","unit":"0","unit":"0","owner":"player6","resource":"4","harvestSpeed":"2"},
{"x":"23","y":"12","unit":"5","unit":"5","owner":"player4","resource":"2","harvestSpeed":"3"},
{"x":"23","y":"13","unit":"0","unit":"0","owner":"player9","resource":"1","harvestSpeed":"3"},
{"x":"23","y":"14","unit":"2","unit":"2","owner":"player7","resource":"3","harvestSpeed":"1"},
{"x":"23","y":"15","unit":"4","unit":"4","owner":"player7","resource":"1","harvestSpeed":"3"},
{"x":"23","y":"16","unit":"3","unit":"3","owner":"player7","resource":"4","harvestSpeed":"1"},
{"x":"23","y":"17","unit":"5","unit":"5","owner":"player1","resource":"2","harvestSpeed":"2"},
{"x":"24","y":"1","unit":"2","unit":"2","owner":"player5","resource":"1","harvestSpeed":"3"},
{"x":"24","y":"2","unit":"3","unit":"3","owner":"player5","resource":"3","harvestSpeed":"1"},
{"x":"24","y":"3","unit":"3","unit":"3","owner":"player4","resource":"1","harvestSpeed":"3"},
{"x":"24","y":"4","unit":"5","unit":"5","owner":"player7","resource":"1","harvestSpeed":"3"},
{"x":"24","y":"5","unit":"1","unit":"1","owner":"player5","resource":"1","harvestSpeed":"2"},
{"x":"24","y":"6","unit":"2","unit":"2","owner":"player6","resource":"2","harvestSpeed":"2"},
{"x":"24","y":"7","unit":"3","unit":"3","owner":"player2","resource":"3","harvestSpeed":"2"},
{"x":"24","y":"8","unit":"1","unit":"1","owner":"player10","resource":"2","harvestSpeed":"1"},
{"x":"24","y":"9","unit":"4","unit":"4","owner":"player10","resource":"1","harvestSpeed":"1"},
{"x":"24","y":"10","unit":"1","unit":"1","owner":"player3","resource":"2","harvestSpeed":"3"},
{"x":"24","y":"11","unit":"1","unit":"1","owner":"player1","resource":"2","harvestSpeed":"1"},
{"x":"24","y":"12","unit":"2","unit":"2","owner":"player3","resource":"1","harvestSpeed":"3"},
{"x":"24","y":"13","unit":"1","unit":"1","owner":"player8","resource":"4","harvestSpeed":"1"},
{"x":"24","y":"14","unit":"0","unit":"0","owner":"player5","resource":"2","harvestSpeed":"2"},
{"x":"24","y":"15","unit":"2","unit":"2","owner":"player6","resource":"2","harvestSpeed":"1"},
{"x":"24","y":"16","unit":"5","unit":"5","owner":"player4","resource":"2","harvestSpeed":"3"},
{"x":"24","y":"17","unit":"5","unit":"5","owner":"player5","resource":"1","harvestSpeed":"1"},
{"x":"25","y":"1","unit":"3","unit":"3","owner":"player6","resource":"2","harvestSpeed":"1"},
{"x":"25","y":"2","unit":"5","unit":"5","owner":"player5","resource":"4","harvestSpeed":"2"},
{"x":"25","y":"3","unit":"3","unit":"3","owner":"player5","resource":"1","harvestSpeed":"1"},
{"x":"25","y":"4","unit":"2","unit":"2","owner":"player9","resource":"4","harvestSpeed":"2"},
{"x":"25","y":"5","unit":"4","unit":"4","owner":"player1","resource":"4","harvestSpeed":"2"},
{"x":"25","y":"6","unit":"3","unit":"3","owner":"player3","resource":"2","harvestSpeed":"3"},
{"x":"25","y":"7","unit":"1","unit":"1","owner":"player9","resource":"2","harvestSpeed":"1"},
{"x":"25","y":"8","unit":"2","unit":"2","owner":"player2","resource":"2","harvestSpeed":"1"},
{"x":"25","y":"9","unit":"5","unit":"5","owner":"player6","resource":"4","harvestSpeed":"1"},
{"x":"25","y":"10","unit":"3","unit":"3","owner":"player7","resource":"1","harvestSpeed":"1"},
{"x":"25","y":"11","unit":"2","unit":"2","owner":"player7","resource":"2","harvestSpeed":"3"},
{"x":"25","y":"12","unit":"3","unit":"3","owner":"player2","resource":"4","harvestSpeed":"3"},
{"x":"25","y":"13","unit":"1","unit":"1","owner":"player2","resource":"4","harvestSpeed":"1"},
{"x":"25","y":"14","unit":"1","unit":"1","owner":"player4","resource":"1","harvestSpeed":"2"},
{"x":"25","y":"15","unit":"5","unit":"5","owner":"player5","resource":"3","harvestSpeed":"1"},
{"x":"25","y":"16","unit":"2","unit":"2","owner":"player1","resource":"1","harvestSpeed":"1"},
{"x":"25","y":"17","unit":"4","unit":"4","owner":"player1","resource":"2","harvestSpeed":"3"},
{"x":"26","y":"1","unit":"0","unit":"0","owner":"player4","resource":"3","harvestSpeed":"3"},
{"x":"26","y":"2","unit":"4","unit":"4","owner":"player10","resource":"4","harvestSpeed":"1"},
{"x":"26","y":"3","unit":"3","unit":"3","owner":"player7","resource":"1","harvestSpeed":"2"},
{"x":"26","y":"4","unit":"4","unit":"4","owner":"player7","resource":"2","harvestSpeed":"3"},
{"x":"26","y":"5","unit":"0","unit":"0","owner":"player1","resource":"1","harvestSpeed":"1"},
{"x":"26","y":"6","unit":"2","unit":"2","owner":"player4","resource":"1","harvestSpeed":"3"},
{"x":"26","y":"7","unit":"0","unit":"0","owner":"player8","resource":"3","harvestSpeed":"2"},
{"x":"26","y":"8","unit":"0","unit":"0","owner":"player4","resource":"1","harvestSpeed":"2"},
{"x":"26","y":"9","unit":"5","unit":"5","owner":"player6","resource":"4","harvestSpeed":"3"},
{"x":"26","y":"10","unit":"0","unit":"0","owner":"player5","resource":"1","harvestSpeed":"3"},
{"x":"26","y":"11","unit":"2","unit":"2","owner":"player3","resource":"2","harvestSpeed":"3"},
{"x":"26","y":"12","unit":"4","unit":"4","owner":"player6","resource":"3","harvestSpeed":"2"},
{"x":"26","y":"13","unit":"1","unit":"1","owner":"player9","resource":"2","harvestSpeed":"3"},
{"x":"26","y":"14","unit":"1","unit":"1","owner":"player5","resource":"2","harvestSpeed":"1"},
{"x":"26","y":"15","unit":"5","unit":"5","owner":"player3","resource":"2","harvestSpeed":"1"},
{"x":"26","y":"16","unit":"0","unit":"0","owner":"player3","resource":"2","harvestSpeed":"2"},
{"x":"26","y":"17","unit":"0","unit":"0","owner":"player10","resource":"2","harvestSpeed":"3"},
{"x":"27","y":"1","unit":"0","unit":"0","owner":"player1","resource":"3","harvestSpeed":"2"},
{"x":"27","y":"2","unit":"4","unit":"4","owner":"player9","resource":"4","harvestSpeed":"3"},
{"x":"27","y":"3","unit":"2","unit":"2","owner":"player4","resource":"2","harvestSpeed":"1"},
{"x":"27","y":"4","unit":"1","unit":"1","owner":"player2","resource":"1","harvestSpeed":"2"},
{"x":"27","y":"5","unit":"5","unit":"5","owner":"player4","resource":"2","harvestSpeed":"2"},
{"x":"27","y":"6","unit":"1","unit":"1","owner":"player5","resource":"4","harvestSpeed":"1"},
{"x":"27","y":"7","unit":"5","unit":"5","owner":"player8","resource":"3","harvestSpeed":"1"},
{"x":"27","y":"8","unit":"5","unit":"5","owner":"player6","resource":"2","harvestSpeed":"2"},
{"x":"27","y":"9","unit":"1","unit":"1","owner":"player4","resource":"2","harvestSpeed":"3"},
{"x":"27","y":"10","unit":"5","unit":"5","owner":"player5","resource":"3","harvestSpeed":"3"},
{"x":"27","y":"11","unit":"0","unit":"0","owner":"player9","resource":"4","harvestSpeed":"2"},
{"x":"27","y":"12","unit":"0","unit":"0","owner":"player9","resource":"2","harvestSpeed":"2"},
{"x":"27","y":"13","unit":"0","unit":"0","owner":"player2","resource":"3","harvestSpeed":"2"},
{"x":"27","y":"14","unit":"1","unit":"1","owner":"player3","resource":"1","harvestSpeed":"2"},
{"x":"27","y":"15","unit":"0","unit":"0","owner":"player6","resource":"2","harvestSpeed":"3"},
{"x":"27","y":"16","unit":"4","unit":"4","owner":"player6","resource":"2","harvestSpeed":"3"},
{"x":"27","y":"17","unit":"0","unit":"0","owner":"player10","resource":"1","harvestSpeed":"3"}
];
	
    var hexHeight,
        hexRadius,
        hexRectangleHeight,
        hexRectangleWidth,
        hexagonAngle = 0.523598776, // 30 degrees in radians
        sideLength = 30,
        boardWidth = 20,
        boardHeight = 20;

    hexHeight = Math.sin(hexagonAngle) * sideLength;
    hexRadius = Math.cos(hexagonAngle) * sideLength;
    hexRectangleHeight = sideLength + 2 * hexHeight;
    hexRectangleWidth = 2 * hexRadius;

    if (canvas.getContext){
        var ctx = canvas.getContext('2d');

        ctx.fillStyle = "#000000";
        ctx.strokeStyle = "#CCCCCC";
        ctx.lineWidth = 1;

        drawBoard(ctx, boardWidth, boardHeight, data);

        canvas.addEventListener("click", function(eventInfo) {
            var x,
                y,
                hexX,
                hexY,
                screenX,
                screenY;

            x = eventInfo.offsetX || eventInfo.layerX;
            y = eventInfo.offsetY || eventInfo.layerY;

            
            hexY = Math.floor(y / (hexHeight + sideLength));
            hexX = Math.floor((x - (hexY % 2) * hexRadius) / hexRectangleWidth);

            screenX = hexX * hexRectangleWidth + ((hexY % 2) * hexRadius);
            screenY = hexY * (hexHeight + sideLength);

            drawBoard(ctx, boardWidth, boardHeight);

            // Check if the mouse's coords are on the board
            if(hexX >= 0 && hexX < boardWidth) {
                if(hexY >= 0 && hexY < boardHeight) {
                    ctx.fillStyle = '#'+Math.floor(Math.random()*16777215).toString(16);

                    drawHexagon(ctx, screenX, screenY, true);
                }
            }
        });
    }

    function drawBoard(canvasContext, width, height, data) {
        var i, j;
		// PROBLEM IS HERE ---------------------------------------------------------
		//$http.get('js/posts.json').success(function(data){//({method: 'GET', url: 'js/posts.json'}).success(function(data) {
		//	$scope.posts = data;
		//	angular.forEach($scope.data, function(value, key){
		//	var json = JSON.parse(data);
		for(i=0;i<data.length;i++){
			console.log("x: "+data[i].x+"  Y: "+data[i].y+"\n");
			switch(data[i].resource){
				case "1": ctx.fillStyle = "#242424"; break;
				case "2": ctx.fillStyle = "#929292"; break;
				case "3": ctx.fillStyle = "#137609"; break;
				case "4": ctx.fillStyle = "#FFD700"; break;
			}
			
			drawHexagon(
				ctx, 
				data[i].x * hexRectangleWidth + ((data[i].y % 2) * hexRadius), 
				data[i].y * (sideLength + hexHeight), 
				false
			);
			/*
			switch(data[i].unit){
				case "0:   	$scope.uint=""; 						break;
				case "1": 	$scope.unit="/sprites/swordsman.png"; 	break;
				case "2": 	$scope.unit="/sprites/archer.png"; 		break;
				case "3": 	$scope.unit="/sprites/pikeman.png"; 	break;
				case "4": 	$scope.unit="/sprites/mage.png"; 		break;
				case "5": 	$scope.unit="/sprites/knight.png"; 		break;
			}
			*/
		}
    }

    function drawHexagon(canvasContext, x, y, fill) {           
        var fill = true;//fill || false;

        canvasContext.beginPath();
        canvasContext.moveTo(x + hexRadius, y);
        canvasContext.lineTo(x + hexRectangleWidth, y + hexHeight);
        canvasContext.lineTo(x + hexRectangleWidth, y + hexHeight + sideLength);
        canvasContext.lineTo(x + hexRadius, y + hexRectangleHeight);
        canvasContext.lineTo(x, y + sideLength + hexHeight);
        canvasContext.lineTo(x, y + hexHeight);
        canvasContext.closePath();

        if(fill) {
            canvasContext.fill();
        } else {
            canvasContext.stroke();
        }
    }

})();